### ISSUE TITLE
Help me to make my awesome profile.

### ISSUE THREAD

**Issue by Marko0513** [GlistenSTAR/GlistenSTAR#2]
Hi, Glisten.
How are you? I saw your github profile and It looks awesome. Can you help me to make like your profile?
Waiting your kindly response.

**Comment by GlistenSTAR** [comment]
Hello @Marko0513, thank you for writing to me! All the necessary information to make 3D contribution is in this link
https://github.com/yoshi389111/github-profile-3d-contrib

1- First, you need to create a personal access token on your account, Go to Account Settings > Developer settings > Personal Access Tokens and click on Generate new token! On note input field, you can write a note for example contribution_3d in order to understand that the generated token is for contribution 3d (later on maybe you are going to have more than one access token and in this way you can distinguish them from one another)! On selected scopes, check repo and workflows and on expiration select, select no expiration! After generating the access token, copy it (keep in mind not to close the tab because there is no way to retrieve again the token once it is created).

2 -Secondly, after you have generated the access token go to your special repository - https://github.com/GlistenSTAR/GlistenSTAR (I suggest opening it in new tab) and create folder workflows and inside it put the action file "profile-3d.yml" - use as reference step 2 on the first link I set you here. Inside the file copy and paste this content (check mine too)
name: GitHub-Profile-3D-Contrib
on:
```
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v2
      - uses: yoshi389111/github-profile-3d-contrib@0.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "generated"
          git push
```
If you want to do commits with your name, keep in mind to replace user.name and user.email

3- Inside this repo go on Settings > Secrets > New Repository Secret and create
Name: GITHUB_TOKEN
Value: Paste the access token you created recently

4- Go to Action Tag - Select GitHub-Profile-3D-Contrib and run workflow manually

5- Go on the README file and add the link of the 3d image you prefer - In my case, I am using it like this
![](./profile-3d-contrib/profile-night-green.svg)

If you have any other question, feel free to ask. Hope I have explained the flow clearly
